[manifest]
version = "1.0.0"
priority = -1

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "if SMODS.has_enhancement(cards_destroyed[i], 'm_glass') then"
position = "at"
payload = "if SMODS.has_enhancement(cards_destroyed[i], 'm_glass') or (SMODS.has_enhancement(cards_destroyed[i], 'm_wild') and SMODS.find_card('j_jdg_rosace')) then"
match_indent = true